Repository prolog-project/prolog-project-backend, pull requests merged in 2024-03, with the labels that each got.

#34 [3차 스프린트] 스케줄러 구현 및 이미지 엔티티 수정
  src/main/java/com/prolog/prologbackend/Config/ScheduledConfig.java
  src/main/java/com/prolog/prologbackend/Notes/Controller/NotesController.java
  src/main/java/com/prolog/prologbackend/Notes/Domain/Image.java
  src/main/java/com/prolog/prologbackend/Notes/Repository/ImageRepository.java
  src/main/java/com/prolog/prologbackend/Notes/Service/NotesServiceImpl.java
  src/main/java/com/prolog/prologbackend/Project/Controller/ProjectController.java
  src/main/java/com/prolog/prologbackend/Project/Service/InvitationEmailService.java
  src/main/java/com/prolog/prologbackend/PrologBackendApplication.java
  src/main/resources/application.properties
  src/test/java/com/prolog/prologbackend/Notes/Controller/NotesControllerTest.java
  src/test/java/com/prolog/prologbackend/Notes/Service/NotesServiceImplTest.java
  src/test/java/com/prolog/prologbackend/Project/Controller/ProjectControllerTest.java
Labels: Feature

#37 [3차 스프린트] 소셜 로그인 및 로그아웃 기능 추가
  src/main/java/com/prolog/prologbackend/Config/SpringSecurityConfig.java
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/KaKaoInfoDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Response/SimpleMemberDto.java
  src/main/java/com/prolog/prologbackend/Member/Domain/Member.java
  src/main/java/com/prolog/prologbackend/Member/Domain/MemberStatus.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberJoinService.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
  src/main/java/com/prolog/prologbackend/Security/Authentication/CustomAuthenticationFilter.java
  src/main/java/com/prolog/prologbackend/Security/Authentication/CustomAuthenticationProvider.java
  src/main/java/com/prolog/prologbackend/Security/Authorization/CustomAuthorizationFilter.java
  src/main/java/com/prolog/prologbackend/Security/ExceptionType/SecurityExceptionType.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/JwtProvider.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/RedisRepository.java
  src/main/java/com/prolog/prologbackend/Security/Logout/CustomLogoutFilter.java
  src/main/java/com/prolog/prologbackend/Security/Logout/CustomLogoutHandler.java
  src/main/java/com/prolog/prologbackend/Security/Logout/CustomLogoutSuccessHandler.java
  src/main/java/com/prolog/prologbackend/Security/UserDetails/CustomUserDetails.java
Labels: Feature

#39 [4차 스프린트] 이메일 중복 기능 수정 및 회원 관련 API 문서화
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/MemberController.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/MemberJoinDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/MemberUpdateDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Response/SimpleMemberDto.java
  src/main/java/com/prolog/prologbackend/Member/Service/AnyMemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
Labels: Docs, Feature

#44 [5차 스프린트] 팀멤버 등록 기능 수정 및 팀멤버 관련 API 문서화
  src/main/java/com/prolog/prologbackend/Config/SwaggerConfig.java
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/ExceptionType/MemberExceptionType.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
  src/main/java/com/prolog/prologbackend/TeamMember/Controller/TeamMemberController.java
  src/main/java/com/prolog/prologbackend/TeamMember/DTO/Request/CreateTeamMemberDto.java
  src/main/java/com/prolog/prologbackend/TeamMember/Service/TeamMemberService.java
Labels: Docs, Feature

#45 [5차 스프린트] 회원 관련 기능 추가
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/SearchMemberController.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/MemberJoinDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/PasswordUpdateDto.java
  src/main/java/com/prolog/prologbackend/Member/Domain/Member.java
  src/main/java/com/prolog/prologbackend/Member/ExceptionType/MemberExceptionType.java
  src/main/java/com/prolog/prologbackend/Member/Repository/MemberRepository.java
  src/main/java/com/prolog/prologbackend/Member/Repository/SearchRedisRepository.java
  src/main/java/com/prolog/prologbackend/Member/Service/AnyMemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/SearchMemberService.java
  src/main/java/com/prolog/prologbackend/Security/Authentication/CustomAuthenticationFilter.java
  src/main/java/com/prolog/prologbackend/Security/Authentication/CustomAuthenticationProvider.java
  src/main/java/com/prolog/prologbackend/Security/ExceptionType/SecurityExceptionType.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/JwtProvider.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/JwtRedisRepository.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/JwtType.java
  src/main/java/com/prolog/prologbackend/Security/Logout/CustomLogoutHandler.java
  src/main/java/com/prolog/prologbackend/Security/UserDetails/CustomUserDetails.java
  src/main/java/com/prolog/prologbackend/TeamMember/Controller/TeamMemberController.java
  src/main/java/com/prolog/prologbackend/TeamMember/Service/TeamMemberService.java
  src/main/resources/templates/issueCertificationNumber.html
  src/main/resources/templates/verificationEmail.html
Labels: Feature

#47 Refactor: "프로젝트 초대 이메일 API 역할부여 수정"
  src/main/java/com/prolog/prologbackend/Project/DTO/Request/InvitationEmailDTO.java
  src/main/java/com/prolog/prologbackend/Project/Service/InvitationEmailService.java
Labels: Refactor, 김광제
