Repository prolog-project/prolog-project-backend, pull requests merged in 2024-04, with the labels that each got.

#48 [6차 스프린트] 이미지 관련 기능 추가
  src/main/java/com/prolog/prologbackend/Member/Controller/MemberController.java
  src/main/java/com/prolog/prologbackend/Member/Domain/Member.java
  src/main/java/com/prolog/prologbackend/Member/ExceptionType/MemberExceptionType.java
  src/main/java/com/prolog/prologbackend/Member/Service/AnyMemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
Labels: Feature

#51 [7차 스프린트] 담당 기능 관련 수정
  src/main/java/com/prolog/prologbackend/Exception/GlobalExceptionHandler.java
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/MemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/SearchMemberController.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/KaKaoInfoDto.java
  src/main/java/com/prolog/prologbackend/Member/Domain/Member.java
  src/main/java/com/prolog/prologbackend/Member/ExceptionType/MemberExceptionType.java
  src/main/java/com/prolog/prologbackend/Member/Service/AnyMemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
  src/main/java/com/prolog/prologbackend/Member/Service/SearchMemberService.java
  src/main/java/com/prolog/prologbackend/Security/Authentication/CustomAuthenticationFilter.java
  src/main/java/com/prolog/prologbackend/Security/Authorization/CustomAuthorizationFilter.java
  src/main/java/com/prolog/prologbackend/Security/ExceptionType/SecurityExceptionType.java
  src/main/java/com/prolog/prologbackend/Security/Jwt/JwtProvider.java
  src/main/java/com/prolog/prologbackend/TeamMember/Domain/TeamMember.java
  src/main/java/com/prolog/prologbackend/TeamMember/Service/TeamMemberService.java
  src/main/resources/templates/issueCertificationNumber.html
  src/main/resources/templates/verificationEmail.html
Labels: Feature

#53 초대 이메일 수정, 프로젝트 조회시 팀멤버 조회, Swagger 파일 일부 수정
  src/main/java/com/prolog/prologbackend/Member/Service/MemberService.java
  src/main/java/com/prolog/prologbackend/Notes/Controller/NotesController.java
  src/main/java/com/prolog/prologbackend/Notes/DTO/Request/RequestNotesDTO.java
  src/main/java/com/prolog/prologbackend/Notes/DTO/Response/ResponseNotesDTO.java
  src/main/java/com/prolog/prologbackend/Notes/DTO/Response/ResponseNotesListDTO.java
  src/main/java/com/prolog/prologbackend/Notes/Service/NotesService.java
  src/main/java/com/prolog/prologbackend/Notes/Service/NotesServiceImpl.java
  src/main/java/com/prolog/prologbackend/Project/Controller/ProjectController.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Request/InvitationEmailDTO.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Request/RequestProjectDetailDTO.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Request/RequestStep.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Response/ProjectListResponseDTO.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Response/ResponseProjectDetailDTO.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Response/ResponseStackImageDTO.java
  src/main/java/com/prolog/prologbackend/Project/DTO/Response/ResponseStackImageListDTO.java
  src/main/java/com/prolog/prologbackend/Project/Service/InvitationEmailService.java
  src/main/java/com/prolog/prologbackend/Project/Service/ProjectService.java
  src/main/java/com/prolog/prologbackend/Project/Service/ProjectServiceImpl.java
  src/main/java/com/prolog/prologbackend/TeamMember/Controller/TeamMemberController.java
  src/main/resources/application.properties
  src/main/resources/templates/InviteEmail.html
  src/test/java/com/prolog/prologbackend/Notes/Controller/NotesControllerTest.java
  src/test/java/com/prolog/prologbackend/Notes/Service/NotesServiceImplTest.java
  src/test/java/com/prolog/prologbackend/Project/Controller/ProjectControllerTest.java
  src/test/java/com/prolog/prologbackend/Project/Service/ProjectServiceImplTest.java
Labels: Refactor, 김광제

#54 담당 기능 API 문서 및 팀멤버 서비스 클래스 수정
  src/main/java/com/prolog/prologbackend/Exception/ErrorResponse.java
  src/main/java/com/prolog/prologbackend/Member/Controller/AnyMemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/MemberController.java
  src/main/java/com/prolog/prologbackend/Member/Controller/SearchMemberController.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/MemberJoinDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/MemberUpdateDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Request/PasswordUpdateDto.java
  src/main/java/com/prolog/prologbackend/Member/DTO/Response/SimpleMemberDto.java
  src/main/java/com/prolog/prologbackend/TeamMember/Controller/TeamMemberController.java
  src/main/java/com/prolog/prologbackend/TeamMember/Service/TeamMemberService.java
Labels: Docs, Feature

#55 로직 수정 및 기능 구현
  src/main/java/com/prolog/prologbackend/Config/ScheduledConfig.java
  src/main/java/com/prolog/prologbackend/Notes/Controller/NotesController.java
  src/main/java/com/prolog/prologbackend/Notes/Service/NotesService.java
  src/main/java/com/prolog/prologbackend/Project/Domain/Project.java
  src/main/java/com/prolog/prologbackend/Project/Domain/ProjectStep.java
  src/main/java/com/prolog/prologbackend/Project/Repository/ProjectRepository.java
  src/main/java/com/prolog/prologbackend/Project/Repository/ProjectStepRepository.java
  src/main/java/com/prolog/prologbackend/Project/Service/ProjectService.java
Labels: Refactor, 김광제
